# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: 'yupana_test'
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - run: |
        pip --version

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip install tox codecov

    - name: Run check manifest
      run: |
        .github/check_manifest.sh

    - name: Run tox
      run: tox
      env:
        DATABASE_SERVICE_NAME: POSTGRES_SQL
        DATABASE_ENGINE: postgresql
        DATABASE_NAME: yupana_test
        POSTGRES_SQL_SERVICE_HOST: localhost
        POSTGRES_SQL_SERVICE_PORT: 5432
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres

    - name: Setup node
      uses: actions/setup-node@v2

    - run: |
        node -v

    - name: Run make command to validate Swagger API
      run: |
        npm install swagger-cli
        node_modules/swagger-cli/swagger-cli.js validate yupana/static/openapi.json
    
    - name: Upload coverage reports to Codecov
      run: |
        codecov
